site_name: cbft Technical Documentation (0.0 DP)

pages:
- ['index.md', 'Home']
- ['dev-guide/overview.md', "Developer's Guide", "Developer's guide overview"]
- ['dev-guide/defining.md', "Developer's Guide", "Defining indexes"]
- ['dev-guide/datasources.md', "Developer's Guide", "Index data sources"]
- ['dev-guide/querying.md', "Developer's Guide", "Queries"]
- ['dev-guide/performance.md', "Developer's Guide", "Performance"]
- ['dev-guide/advanced.md', "Developer's Guide", "Advanced topics"]
- ['dev-guide/samples.md', "Developer's Guide", "Sample apps"]
- ['api-ref.md', "API Reference"]
- ['admin-guide/overview.md', "Administrator's Guide", "Administrator's guide overview"]
- ['admin-guide/planning.md', "Administrator's Guide", "Planning your deployment"]
- ['admin-guide/dependencies.md', "Administrator's Guide", "Dependencies"]
- ['admin-guide/running.md', "Administrator's Guide", "Running cbft"]
- ['admin-guide/clustering.md', "Administrator's Guide", "Clustering cbft"]
- ['admin-guide/index-management.md', "Administrator's Guide", "Index management"]
- ['admin-guide/monitoring.md', "Administrator's Guide", "Monitoring cbft"]
- ['admin-guide/diagnosing.md', "Administrator's Guide", "Diagnosing issues"]
- ['links.md', "Links"]

copyright: Copyright &copy; 2015, <a href="http://couchbase.com">Couchbase, Inc.</a>.

theme: flatly